baseURL: "https://suryansh-codes2209.github.io/"
languageCode: "en-us"
title: "Suryansh Profile"
theme: hugo-profile

Paginate: 3
disqusShortname: Ansh
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true



    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Suryansh's Portfolio"
  description: Description
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Suryansh Chaudhary"
    subtitle: "CSE-AI Student"
    content: "A passionate developer | AI/ML Enthusiast | Youtuber."
    image: /images/hero.jpg
    button:
      enable: true
      name: "Resume"
      url: "/Suryansh's Resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Suryansh-Codes2209
        - icon: fab fa-twitter
          url: https://twitter.com/Suryansh_2001?t=s20BQLgfOStsoKcf32U3lA&s=09
        - icon: fab fa-youtube
          url: https://www.youtube.com/channel/UChkVl0fauckxjTimXInRmrQ 
      customIcons:
        - icon: /fav.png
          url: "https://www.cloudskillsboost.google/public_profiles/3666ff31-fbbe-480e-9872-200b614f7feb"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a undergraduate student . I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently diving into AI/ML field to get as much as knowledge into that vast horizon.   

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Python"
        - "Bootstrap"
        - "Java"

  # Experience
  experience:
    enable: true
    items:
      - job: "AI/ML Intern"
        company: "Ongraph"
        companyUrl: "https://www.ongraph.com/"
        date: "July 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a AI/ML developer at Ongraph Technologies Pvt LTD in Noida ,Uttar pradesh. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Intern as Tutor"
        company: "Atal Tinkering Labs"
        companyUrl: "https://aim.gov.in/atl.php"
        date: "July 2022 - present"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as Mentor.
        content: |
          In ATL I have a specific role to teach school students which are looking forwarding in technologies . what is Artificial Intelligence / Machine learning . what its future
          scope.

  # Education
  education:
    enable: true
    # index: true
    items:
      
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Poornima Group of Institutions"
          url: "https://www.poornima.org/"
        date: "2020 - 2024"
        GPA: "9.0 out of 10.0"
        content: |-
          - RTU Poornima Hackathon (03/2021 - 03/2021)
          - Hands-on-workshop on IOT with xpecto IIT Mandi
          - Workshop on Artificial N Dimensions : A.I. Ethics By COE Big Data
 
 
 
 
  # Achievements
  achievements:
    enable: true
    items:
      - title: 30 days of google cloud program 2021
        content: Learn about Cloud Technologies from Google 
        url: https://verification.givemycertificate.com/v/72c77885-f17e-4ab9-a2fc-f250a0133613
      - title: Microsoft Certified Azure Data Fundamentals
        content: Completion in Azure
        url: https://www.credly.com/badges/69b5ebeb-38a0-44af-a675-dc6c184dad34 
      - title: Microsoft Certified Azure AI Data Fundamentals
        content: Completion in Azure AI Fundamentals 
        url: https://www.credly.com/badges/6ff82d44-507a-4a67-b304-0ff9ebad63e8



  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: suryansh.codes2001@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/Suryansh-Codes2209
      linkedin: https://www.linkedin.com/in/suryansh-chaudhary-2209
      twitter: https://twitter.com/Suryansh_2001?t=s20BQLgfOStsoKcf32U3lA&s=09
      instagram: https://instagram.com/chaudhary_suryansh?igshid=YmMyMTA2M2Y=
     
